// ============================================================
// sobel_tb.v — Testbench for Sobel Edge Detector
// ============================================================
// 1. Reads grayscale pixels from input.hex ($readmemh)
// 2. Streams one pixel per clock into the sobel module
// 3. Captures output pixels when out_valid is high
// 4. Writes results to output.hex
// 5. Dumps VCD waveform for gtkwave
// ============================================================

// IMG_WIDTH / IMG_HEIGHT can be passed at compile time via iverilog -D flags.
// Defaults match the standard 64x64 test images generated by generate_test_images.py.
`ifndef IMG_WIDTH
  `define IMG_WIDTH 64
`endif
`ifndef IMG_HEIGHT
  `define IMG_HEIGHT 64
`endif

`timescale 1ns / 1ps

module sobel_tb;

    localparam W = `IMG_WIDTH;
    localparam H = `IMG_HEIGHT;
    localparam NUM_PIXELS = W * H;
    localparam THRESHOLD  = 80;

    // -- Clock & reset --
    reg clk;
    reg rst;

    // -- DUT signals --
    reg  [7:0] pixel_in;
    reg        pixel_valid;
    wire [7:0] pixel_out;
    wire       out_valid;

    // -- Pixel storage --
    reg [7:0] img_in  [0:NUM_PIXELS-1];

    // -- Output capture --
    integer out_file;
    integer out_count;

    // -- Pixel feed counter --
    integer feed_idx;

    // -- Instantiate the Sobel module --
    sobel #(
        .IMG_W     (W),
        .IMG_H     (H),
        .THRESHOLD (THRESHOLD)
    ) dut (
        .clk         (clk),
        .rst         (rst),
        .pixel_in    (pixel_in),
        .pixel_valid (pixel_valid),
        .pixel_out   (pixel_out),
        .out_valid   (out_valid)
    );

    // -- Clock generation: 10 ns period --
    initial clk = 0;
    always #5 clk = ~clk;

    // -- Main test sequence --
    initial begin
        // Waveform dump — disabled with -DNO_VCD for production runs
`ifndef NO_VCD
        $dumpfile("sobel.vcd");
        $dumpvars(0, sobel_tb);
`endif

        // Load input image
        $readmemh("input.hex", img_in);

        // Open output file
        out_file  = $fopen("output.hex", "w");
        out_count = 0;

        // Reset
        rst         = 1;
        pixel_in    = 0;
        pixel_valid = 0;
        feed_idx    = 0;

        @(posedge clk);
        @(posedge clk);
        rst = 0;
        @(posedge clk);

        // Stream all pixels, one per clock
        while (feed_idx < NUM_PIXELS) begin
            @(posedge clk);
            pixel_in    <= img_in[feed_idx];
            pixel_valid <= 1;
            feed_idx    = feed_idx + 1;
        end

        // De-assert valid and let the pipeline drain
        @(posedge clk);
        pixel_valid <= 0;

        // Wait extra cycles for the last output to emerge
        repeat (10) @(posedge clk);

        $fclose(out_file);
        $display("Simulation complete: %0d output pixels written to output.hex", out_count);
        $display("Expected: %0d  (= %0d x %0d)", (W-2)*(H-2), W-2, H-2);
        $finish;
    end

    // -- Capture output pixels on every out_valid --
    always @(posedge clk) begin
        if (out_valid) begin
            $fwrite(out_file, "%02X\n", pixel_out);
            out_count = out_count + 1;
        end
    end

endmodule
